/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomClock {
    }
    interface MyCard {
        "fact": string;
    }
    interface ParentCard {
    }
}
declare global {
    interface HTMLCustomClockElement extends Components.CustomClock, HTMLStencilElement {
    }
    var HTMLCustomClockElement: {
        prototype: HTMLCustomClockElement;
        new (): HTMLCustomClockElement;
    };
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLParentCardElement extends Components.ParentCard, HTMLStencilElement {
    }
    var HTMLParentCardElement: {
        prototype: HTMLParentCardElement;
        new (): HTMLParentCardElement;
    };
    interface HTMLElementTagNameMap {
        "custom-clock": HTMLCustomClockElement;
        "my-card": HTMLMyCardElement;
        "parent-card": HTMLParentCardElement;
    }
}
declare namespace LocalJSX {
    interface CustomClock {
    }
    interface MyCard {
        "fact"?: string;
    }
    interface ParentCard {
    }
    interface IntrinsicElements {
        "custom-clock": CustomClock;
        "my-card": MyCard;
        "parent-card": ParentCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-clock": LocalJSX.CustomClock & JSXBase.HTMLAttributes<HTMLCustomClockElement>;
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "parent-card": LocalJSX.ParentCard & JSXBase.HTMLAttributes<HTMLParentCardElement>;
        }
    }
}
